### ISSUE TITLE
Implement Blog Post Functionality in Backend

### ISSUE THREAD

**Issue by shino022** [AmeerSyed7340/Blog#1]
### Description
We need to set up backend functionality for managing blog posts. This involves creating a Mongoose model, defining routes, and implementing controllers for CRUD operations. Each endpoint should be properly validated and integrated with our MongoDB database.

### Tasks

- [x] **Create `Blog.js` in the `models` Directory**
  - Define the Mongoose schema for blog posts with these fields:
    - `postID` (Primary Key): Unique identifier for each post.
    - `username` (Foreign Key): Reference to the username in the Users collection.
    - `title`: Title of the blog post.
    - `content`: Body of the blog post.
    - `createdAt`: Timestamp of post creation.

- [x] **Set Up Routes in the `routes` Folder**
  - Create a `blogRoutes.js` file.
  - Define routes that map to the specified endpoints.
  - Each route should call the appropriate controller method.

- [x] #2
  - Create a `blogController.js` file.
  - Implement functions for each CRUD operation.
  - Each function should interact with the `Blog` model to perform database operations.

### API Endpoints and Implementation Details

- [x] **GET `/read` - Read All Posts**
  - Controller function should retrieve all posts from the database.
  - Ensure proper error handling and response formatting.
  - Response format:
    ```json
    {
      "posts": [<post>, <post>, ...]
    }
    ```

- [x] **GET `/read/:postID` - Read a Single Post**
  - Controller function should fetch a post by `postID`.
  - Validate `postID` before querying the database.
  - Handle cases where the post does not exist.
  - Response format:
    ```json
    {
      "post": <post>
    }
    ```

- [x] **POST `/posts` - Create a New Post**
  - Controller function should create a new post with provided data.
  - Validate input data (title, content, username) before saving to the database.
  - `createdAt` should be set automatically to the current date and time.
  - Response should confirm successful creation.

### Additional Notes
- Validation is crucial. Ensure all inputs are validated both for type and content (e.g., no empty titles).
- Error handling in controllers should cover database errors and validation failures.
- Test each endpoint with various scenarios, including edge cases.

**Comment by Chuan-Chen** [comment]
- [x]  **blogController.updateBlog**
    - create update end-point
    - make sure you can update blog with the right credentials
- [x] **blogController.deleteBlog**
    - delete blog endpoint
    - make sure it can delete blog with the right credentials
