### ISSUE TITLE
Fix error

### ISSUE THREAD

**Issue by AmeerSyed7340** [AmeerSyed7340/Blog#3]
**Tasks**

- [x] Fix Login dialog as it sometimes still shows error after using correct credentials.
- [x] #5
- [x] PostID needs to increment after each successful db insertion. Must happen in the backend
- [ ] If i have to scroll down in homepage to check a blog then the scroll bar doesnt reset back to top on read page.

**Comment by Chuan-Chen** [comment]
having the page stayed logged in we will need to cache the user with some type of auth caching maybe just caching the pass and user will do for now.

**Comment by AmeerSyed7340** [comment]
> having the page stayed logged in we will need to cache the user with some type of auth caching maybe just caching the pass and user will do for now.

Sounds good. Lets leave that for the end.
